sudo: required
language: node_js
dist: trusty
language: node_js
node_js:
  - node
script: npm run coverage
after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info